site_name: RAG Project Documentation
site_description: Documentation for RAG-based Bachelor's Thesis
site_author: Martin Lejko

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_category_heading: true
            show_root_heading: true

nav:
  - Home: index.md
  - API Reference:
      - Proof of Concept: api/proof_of_concept.md
      - Common Utilities: api/common.md
      - Data Ingestion: api/ingestion.md
      - Document Processing: api/processing.md
      - RAG Pipeline: api/rag_pipeline.md
      - Evaluation: api/evaluation.md
      - Testing: api/testing.md
      - Iterations: api/iterations.md